### Exploring Covid in Africa

<a id="cont"></a>

### Table of Contents

<a href=#one>1. Packages</a>

In [4]:
import warnings
warnings.filterwarnings("ignore", category=RuntimeWarning) 

import numpy as np 
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

import sklearn

In [6]:
data = pd.read_csv('covid_africa.csv', index_col=0)

In [7]:
data.head(5)

,Total Cases,Total Deaths,Total Recovered,Active Cases,Tot Cases/ 1M pop,Deaths/ 1M pop,Total Tests,Tests/ 1M pop,Population
Country/Other,,,,,,,,,
Algeria,265739,6874,178335.0,80530.0,5870,152,230861.0,5100.0,45267027
Angola,99194,1900,97149.0,145.0,2859,55,1499795.0,43230.0,34693502
Benin,26952,163,25506.0,1283.0,2124,13,604310.0,47618.0,12690836
Botswana,305859,2688,303026.0,145.0,125531,1103,2026898.0,831880.0,2436528
Burkina Faso,20853,382,20439.0,32.0,951,17,248995.0,11355.0,21927855

In [8]:
data.describe()

,Total Cases,Total Deaths,Total Recovered,Active Cases,Tot Cases/ 1M pop,Deaths/ 1M pop,Total Tests,Tests/ 1M pop,Population
count,5.400000e+01,54.000000,5.000000e+01,50.000000,54.000000,54.000000,5.100000e+01,51.000000,5.400000e+01
mean,2.116154e+05,4675.370370,1.928952e+05,8442.300000,23966.555556,304.222222,1.938529e+06,158502.568627,2.585486e+07
std,5.404438e+05,14310.867875,5.323413e+05,19540.534398,61163.285804,511.350696,3.743918e+06,215620.789351,3.733978e+07
min,5.948000e+03,38.000000,7.730000e+02,1.000000,344.000000,3.000000,2.369300e+04,5100.000000,9.943600e+04
25%,2.165950e+04,278.250000,1.547725e+04,39.250000,2322.500000,32.000000,3.267945e+05,28016.000000,2.875945e+06
50%,5.733550e+04,983.500000,4.910500e+04,673.000000,4523.000000,92.000000,6.601070e+05,60375.000000,1.364788e+07
75%,1.633135e+05,3029.250000,1.581335e+05,3666.750000,16008.000000,225.500000,2.127916e+06,202866.500000,3.141540e+07
max,3.741230e+06,100147.000000,3.627594e+06,82778.000000,418963.000000,2368.000000,2.418901e+07,854779.000000,2.152734e+08